@url = https://effective-halibut-vxjp6j4x497c6xpr-8080.app.github.dev/alunos

GET {{url}}

###

POST {{url}}
Content-Type: application/json

{
    "nome" : "Leo",
    "idade" : 30
}

###

PUT {{url}}/2
Content-Type: application/json

{
    "nome" : "luffy",
    "idade" : 90
}

###

DELETE {{url}}/3

###

GET {{url}}/4